# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

var_1: &cache_key yarn-cache-{{ checksum "yarn.lock" }}-0.12.11
var_2: &run_in_node
  docker:
    - image: circleci/node:12.9.1

jobs:
  install:
    <<: *run_in_node
    steps:
      - checkout
      - restore_cache:
          keys:
            - *cache_key
      - run: yarn --frozen-lockfile --non-interactive
      - save_cache:
          key: *cache_key
          paths:
            - node_modules

  build-all:
    <<: *run_in_node
    steps:
      - checkout

      # - restore_cache:
      #     keys:
      #       - *cache_key
      - run: yarn
      - run:
          name: Build all packages
          command: yarn affected:test --all --parallel

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-all:
          # requires:
          #   - install
          filters:
            tags:
              only: /.*/
